"""updeate comments

Revision ID: 504ae72d7179
Revises: 42cde6c2019c
Create Date: 2025-02-06 11:03:02.319921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '504ae72d7179'
down_revision: Union[str, None] = '42cde6c2019c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'id')
    # ### end Alembic commands ###
