"""testmigragtion

Revision ID: e6c9b18b5115
Revises: 504ae72d7179
Create Date: 2025-02-06 16:23:11.357742

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e6c9b18b5115"
down_revision: Union[str, None] = "504ae72d7179"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "comment",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
